# -*- coding: utf-8 -*-
"""
/***************************************************************************
 nmea2qgis3
                                 A QGIS plugin
 Plugin importing nmea data into the qgis program
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-07-19
        copyright            : (C) 2018 by Piotr Zyto
        email                : zidopiotr@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load nmea2qgis3 class from file nmea2qgis3.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .nmea2_qgis3 import nmea2qgis3
    return nmea2qgis3(iface)
